#:kivy 1.0.9
#:set gui_path "./../data/gui"
<StartMenu>:
    # canvas.before:
    #     BorderImage:
    #         # BorderImage behaves like the CSS BorderImage
    #         border: 10, 10, 10, 10
    #         source: 'robostep.jpg'
    #         pos: self.pos
    #         size: self.size

    FloatLayout:
        id: layout
        AppMenu:
            id: com_menu
            top: root.height
            cancel_handler_widget: layout
            
            AppMenuTextItem:
                text: "MENU"
                on_release:
                    root.search_com_port()
                ContextMenu:
                    ContextMenuTextItem:
                        text: "Setting"
                        ContextMenu:
                            ContextMenuTextItem:
                                text: "parts"
                                on_release:
                                    root.manager.transition.direction = 'right' 
                                    root.manager.current = 'parts'
                            ContextMenuTextItem:
                                text: "mode"
                                ContextMenu:
                                    ContextMenuTextItem:
                                        text: "nomal"
                                        on_release: root.nomal_mode()
                                    ContextMenuTextItem:
                                        text: "extra"
                                        on_release: root.extra_mode()
                    ContextMenuTextItem:
                        text: "port"
                        id: select_number
                        ContextMenu:
                            id: com_port
                            ContextMenuTextItem:
                                text: "none"
                    ContextMenuTextItem:
                        text: "EXIT"
                        on_release:
                            on_press: app.stop()
            AppMenuTextItem:
                id: com
                pos_hint: {"right":1}
                text: "                                     COM:NO CONECCTION"
                color: 1,0,0,1

    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: 0.2
            Label:
                text: ""
        BoxLayout:
            orientation: 'horizontal'                  
            BoxLayout:
                id: slider_mode
                size_hint_x: 0.5
                size_hint_y: 0.8
                pos_hint: {"center_x":0.1,"center_y":2}
                orientation: "vertical"
                
                FloatLayout:
                    Image:
                        id: wifi
                        size_hint_x: 2.3
                        size_hint_y: 2.3
                        pos_hint: {"center_x":0.5,"center_y":-19}
                        source: gui_path + '/robostep.jpg'
                
                Label:
                    size_hint_y: 0.3
                    font_size: 25
                    text: "Paramerter"
                Slider:
                    id: slider_gray
                    min: 0
                    max: 255
                    step: 1
                    value: 100
                    orientation: 'horizontal'
                    on_touch_up:
                        root.param_save()
                Label:
                    size_hint_y: 0.3
                    text: "Gray threshold:" + str("{:d}".format(int(slider_gray.value)))
                Slider:
                    id: slider_pwm
                    min: 0
                    max: 1
                    step: 0.1
                    value: 0.5
                    orientation: 'horizontal'
                Label:
                    size_hint_y: 0.3
                    text: "Electromagnet strength:" +  str("{:.1}".format(slider_pwm.value))
                Slider:
                    id: slider_speed
                    min: 0
                    max: 1
                    step: 0.1
                    value: 0.5
                    orientation: 'horizontal'
                Label:
                    size_hint_y: 0.3
                    text: "Speed:" + str("{:.1}".format(slider_speed.value))
                Switch:
                    id: switch
                Label:
                    size_hint_y: 0.3
                    text: "Slack:" + str(switch.active)
                Label:
                    size_hint_y: 0.5
                    text: ""
                Button:
                    size_hint_y: 0.5
                    text: "reset"
                    
            BoxLayout:
                orientation: "vertical"
                #padding: 0
                #spacing: 1
                # pos_hint: {"x":0.9}
                # size_hint: 1, 0.1
                Image:
                    id: camera_1
                    pos_hint: {"center_x":6,"center_y":0.9}
                    size_hint: None, None
                    size: 900, 450
                Label:
                    height: "25dp"
                    font_size: 25
                    text: "       sample1"
            BoxLayout:
                orientation: "vertical"
                # pos_hint: {"center_x":0.9}
                BoxLayout:
                    orientation: "vertical"
                    # padding: 0
                    # spacing: 1
                    # size_hint: 1, 0.1
                    Image:
                        pos_hint: {"center_x":2}
                        id: camera_2
                        size_hint: None, None
                        size: 400, 200
                    Label:
                        size_hint_y: 0.1
                        font_size: 20
                        text: "           sample2"
                BoxLayout:
                    orientation: "vertical"
                    # padding: 0
                    # spacing: 1
                    # size_hint: 1, 0.1
                    Image:
                        pos_hint: {"center_x":2}
                        id: camera_3
                        size_hint: None, None
                        size: 400, 200
                    Label:
                        size_hint_y: 0.1
                        font_size: 20
                        text: "           sample3"

        Button:
            text: 'Play'
            size_hint_y: None
            height: '48dp'
            on_press: root.play()



