#:kivy 1.0.9
#:set gui_path "./../data/gui"

<StartMenu>:
    canvas.before:
        BorderImage:
            # BorderImage behaves like the CSS BorderImage
            border: 10, 10, 10, 10
            source:  gui_path + '/sozai/back.jpg'
            pos: self.pos
            size: self.size

    FloatLayout:
        size_hint_y: 0.1
        pos_hint: {"top":1}
        AppMenu:
            id: com_menu
            size_hint_y: 1
            pos_hint: {"top":1}   
            canvas.before:
                Color:
                    rgb: 1, .753, 0
                Rectangle:
                    pos: self.pos
                    size: self.size
            AppMenuTextItem:
                text: "     "
                background_nomal: gui_path + '/sozai/BG_yellow.jpg'
                background_down: gui_path + '/sozai/BG_yellow.jpg'
                background_up: gui_path + '/sozai/BG_yellow.jpg'
                background_color: 1, .753, 0
                size_hint_y: 1
                font_size: 34
                on_release:
                    root.search_com_port()
                ContextMenu:
                    ContextMenuTextItem:
                        text: "parts"
                        size: 10,30
                        font_size: 26
                        on_release:
                            root.manager.transition.direction = 'right' 
                            root.manager.current = 'parts'
                    ContextMenuTextItem:
                        text: "port"
                        size: 10,30
                        font_size: 26
                        id: select_number
                        ContextMenu:
                            id: com_port
                            ContextMenuTextItem:
                                text: "none"
                    ContextMenuTextItem:
                        text: "EXIT"
                        size: 10,30
                        font_size: 26
                        on_release:
                            on_press: app.stop()
            
    FloatLayout:
        orientation: 'horizontal'
        size_hint_y: 0.9
        size_hint_x: 0.35
        pos: 0,650*0.9
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                size_hint_x: 0.1
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.8
                Label:
                    size_hint_y: 1
                    font_size: 32
                    font_name: gui_path + "/font/arialbd.ttf"
                    text: "Paramerter"
                BoxLayout:
                    size_hint_y: 0.1
                    Label:
                        text:""
                BoxLayout:
                    canvas.before:
                        BorderImage:
                            source: gui_path + '/sozai/BG_yellow.jpg'
                            pos: self.pos
                            size: self.size
                    Label:
                        font_name: gui_path + "/font/arialbd.ttf"
                        text: "Gray Threshold"
                        font_size: 24
                        color: 255,255,255,1
                BoxLayout:
                    orientation: 'horizontal'
                    Slider:
                        id: slider_gray
                        size_hint_x: 0.8
                        min: 0
                        max: 255
                        value: 127
                        step: 1
                        orientation: 'horizontal'
                        on_touch_up:
                            root.param_save()
                            root.threshold_test()
                    Label:
                        size_hint_y: 1
                        size_hint_x: 0.2
                        text: str(int(slider_gray.value))
                        font_size: 18

                BoxLayout:
                    size_hint_y: 0.1
                    Label:
                        text:""
                BoxLayout:
                    canvas.before:
                        BorderImage:
                            source: gui_path + '/sozai/BG_yellow.jpg'
                            pos: self.pos
                            size: self.size
                    Label:
                        font_name: gui_path + "/font/arialbd.ttf"
                        text: "Magnetic Force \n for Picking"
                        font_size: 24
                        color: 255,255,255,1
                BoxLayout:
                    orientation: 'horizontal'
                    Slider:
                        id: slider_pwm
                        min: 0
                        max: 0.9
                        value: 0.3
                        step: 0.1
                        size_hint_x: 0.8
                        orientation: 'horizontal'
                        on_touch_up:
                            root.param_save()
                    Label:
                        size_hint_y: 1
                        size_hint_x: 0.2
                        text: str("{:.1}".format(slider_pwm.value))
                        font_size: 18
                BoxLayout:
                    size_hint_y: 0.1
                    Label:
                        text:""
                BoxLayout:
                    canvas.before:
                        BorderImage:
                            source: gui_path + '/sozai/BG_yellow.jpg'
                            pos: self.pos
                            size: self.size
                    Label:
                        font_name: gui_path + "/font/arialbd.ttf"
                        text: "Magnetic Force \n for Ceparation"
                        font_size: 24
                        color: 255,255,255,1
                BoxLayout:
                    orientation: 'horizontal'
                    Slider:
                        id: slider_speed
                        min: 0
                        max: 0.9
                        value: 0.3
                        step: 0.1
                        size_hint_x: 0.8
                        orientation: 'horizontal'
                        on_touch_up:
                            root.param_save()
                    Label:
                        size_hint_y: 1
                        size_hint_x: 0.2
                        text: str("{:.1}".format(slider_speed.value))
                        font_size: 18
            BoxLayout:
                size_hint_x: 0.1




    FloatLayout:
        canvas.before:
            BorderImage:
                source: gui_path + '/sozai/BG_yellow.jpg'
                pos: 0,650-65
                size: 150,65
        Image:
            source: gui_path + "/sozai/MenuButton.png"
            size_hint: None, None
            size: 50, 50
            pos_hint: {'x': 0.02, 'y': 0.91}

    FloatLayout:
        Label:
            font_name: gui_path + "/font/arial.ttf"
            text: "START / STOP"
            font_size: 24
            color: 255,255,255,1
            pos: 440, -100

    FloatLayout:
        canvas.before:
            PushMatrix
            Rotate:
                # angle: root.angle
                axis: 0, 0, 1
                origin: root.center
        canvas.after:
            PopMatrix
        on_touch_down:
            # root.emergency_button_on()
        Image:
            source: gui_path + "/sozai/EmergencySwitch.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.8, 'y': 0.08}


    FloatLayout:
        Image:
            source: gui_path + "/sozai/DCHackLogo.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.85, 'y': 0.83}

    FloatLayout:
        canvas.before:
            PushMatrix
            Rotate:
                # angle: root.angle
                axis: 0, 0, 1
                origin: root.center
        canvas.after:
            PopMatrix
        Image:
            source: gui_path + "/sozai/hackathon.png"
            size_hint: None, None
            size: 30, 30
            pos_hint: {'x': 0.914, 'y': 0.934}

    FloatLayout:
        Image:
            id: wifi_icon
            source: gui_path + "/sozai/Network_ON_Color.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.75, 'y': 0.83}
        
    FloatLayout:
        on_touch_down:
            root.slack_button_down()

        Image:
            id: slack_icon
            source: gui_path + "/sozai/Slack_ON_Color.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.7, 'y': 0.83}
        
    FloatLayout:
        Image:
            id: line_icon
            source: gui_path + "/sozai/LINE_ON_Color.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.65, 'y': 0.83}
        # on_touch_down:
        #     root.line_button_down()

    FloatLayout:
        on_touch_down:
            root.googlesheet_down()
        Image:
            id: googlesheet_icon
            source: gui_path + "/sozai/GoogleSheet_ON_Color.png"
            size_hint: None, None
            size: 150, 150
            pos_hint: {'x': 0.6, 'y': 0.83}



    FloatLayout:
        Label:
            id: port_name
            font_name: gui_path + "/font/arialbd.ttf"
            text: "COM:"
            font_size: 24
            color: 255,255,255,1
            pos: 0, 290

    # FloatLayout:
    #     canvas.before:
    #         BorderImage:
    #             source: gui_path + '/sozai/BG_yellow.jpg'
    #             pos: 660-264*1.8/2,150-154*1.8/2
    #             size: 264*1.8,154*1.8

    # FloatLayout:
    #     canvas.before:
    #         BorderImage:
    #             source: gui_path + '/sozai/BG_yellow.jpg'
    #             pos: 980-154*1.8/2,450-154
    #             size: 154*1.8,154*1.8

    FloatLayout:
        orientation: "vertical"
                # padding: 0
                # spacing: 1
                # size_hint: 1, 0.1
        Image:
            pos: 640-264*1.8/2,150-154*1.8/2
            id: ar_img
            size_hint: None, None
            size: 264*1.8,154*1.8
            source: gui_path + '/sozai/BG_yellow.jpg'

    FloatLayout:
        orientation: "vertical"
        Image:
            id: roi_img
            size_hint: None, None
            size: 184*1.8,154*1.8
            pos: 660-224,450-154
            source: gui_path + '/sozai/BG_yellow.jpg'
    
    FloatLayout:
        orientation: "vertical"
        Image:
            id: target_img
            size_hint: None, None
            size: 154*1.8,154*1.8
            pos: 1120-154*1.8/2,450-154
            source: gui_path + '/sozai/BG_yellow.jpg'

    
