#:kivy 1.0.9

<StartMenu>:
    canvas:
        Rectangle:
            source: 'robostep.jpg'
            size: self.width, self.height

    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*1.25 - self.width
        center_y: root.center_y*0.75 - self.width
        text: 'SET'
        on_release:
            root.manager.transition.direction = 'left' 
            root.manager.current = 'set'

    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*0.8 - self.width
        center_y: root.center_y*0.75 - self.width
        text: 'ACT'
        on_release:
            root.manager.transition.direction = 'right' 
            root.manager.current = 'act'
    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*1.25 - self.width
        center_y: root.center_y - self.width
        text: 'TEXT'
        on_release:
            root.manager.transition.direction = 'right' 
            root.manager.current = 'text'
    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*0.8 - self.width
        center_y: root.center_y - self.width
        text: 'TEST'
        on_release:
            root.manager.transition.direction = 'left' 
            root.manager.current = 'test'
    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x + self.width + 150
        center_y: root.center_y - self.width - 80
        text: 'END'
        on_press: app.stop()

<SettingScreen>:
    canvas:
        Rectangle:
            source: 'image/start_background.jpg'
            size: self.width, self.height

    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x - self.width
        center_y: root.center_y
        text: 'BACK'
        on_release:
            root.manager.transition.direction = 'right' 
            root.manager.current = 'start'

<ActionScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            padding: 0
            spacing: 1
            size_hint: 1, 0.1
            Image:
                id: camera
                size_hint: None, None
                size: 1000, 500

        Button:
            text: 'Play'
            size_hint_y: None
            height: '48dp'
            on_press: root.play()
        Button:
            text: 'Capture'
            size_hint_y: None
            height: '48dp'
            on_press: root.capture()


<BoxConfig>:

    orientation: "horizontal"
    slider_d: slider_d

    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x - self.width
        center_y: root.center_y*0.9
        text: 'Back'
        on_release:
            root.manager.transition.direction = 'left' 
            root.manager.current = 'start'
    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*2 - self.width
        center_y: root.center_y*0.9
        text: 'FIN'
        on_release:
            root.get_text_a()
            root.get_text_b()
            root.get_text_c()
            root.get_text_d()
            root.save()
            
    BoxLayout:
        pos_hint:{"left":1, "top":1}
        size_hint_x: 0.5
        size_hint_y: 0.4
        orientation: "vertical"
        Label:
            size_hint_y: 0.3
            text: str("A_parts")
        BoxLayout:
            BoxLayout:
                Image:
                    source: 'sample1.jpg'
            Slider:
                id: slider_a
                min: 0
                max: 50
                step: 5
                value: 25
                orientation: 'vertical'
                size_hint_x:0.3        
            Label:
                size_hint_x: 0.1
                text: str(slider_a.value)
        BoxLayout:
            size_hint_y: 0.2
            Label:
                size_hint_x: 0.2
                text: str("name")
            TextInput:
                text:"Hello World"
                size_hint_x:0.3
                color:1,0,0,1
                id: text_a
                multiline: False
                on_text_validate: root.get_text_a()
            Button:
                size_hint_x: 0.2
                text: "ok"
                on_release:
                    root.get_text_a()
            Label:
                size_hint_x: 0.2
                text: str("length")

    BoxLayout:
        pos_hint:{"left":1, "bottom":1}
        size_hint_x: 0.5
        size_hint_y: 0.4
        orientation: "vertical"
        Label:
            size_hint_y: 0.3
            text: str("B_parts")
        BoxLayout:
            BoxLayout:
                Image:
                    source: 'sample1.jpg'
            Slider:
                id: slider_b
                min: 0
                max: 50
                value: 25
                step: 5
                orientation: 'vertical'
                size_hint_x:0.3        
            Label:
                size_hint_x: 0.1
                text: str(slider_b.value)
        BoxLayout:
            size_hint_y: 0.2
            Label:
                size_hint_x: 0.2
                text: str("name")
            TextInput:
                text:"Hello World"
                size_hint_x:0.3
                color:1,0,0,1
                id: text_b
                multiline: False
                on_text_validate: root.get_text_b()
            Button:
                size_hint_x: 0.2
                text: "ok"
                on_release:
                    root.get_text_b()
            Label:
                size_hint_x: 0.2
                text: str("length")

    BoxLayout:
        pos_hint:{"right":1, "bottom":1}
        size_hint_x: 0.5
        size_hint_y: 0.4
        orientation: "vertical"
        Label:
            size_hint_y: 0.3
            text: str("C_parts")
        BoxLayout:
            BoxLayout:
                Image:
                    source: 'sample1.jpg'
            Slider:
                id: slider_c
                min: 0
                max: 50
                value: 25
                step: 5
                orientation: 'vertical'
                size_hint_x:0.3        
            Label:
                size_hint_x: 0.1
                text: str(slider_c.value)
        BoxLayout:
            size_hint_y: 0.2
            Label:
                size_hint_x: 0.2
                text: str("name")
            TextInput:
                text:"Hello World"
                size_hint_x:0.3
                color:1,0,0,1
                id: text_c
                multiline: False
                on_text_validate: root.get_text_c()
            Button:
                size_hint_x: 0.2
                text: "ok"
                on_release:
                    root.get_text_c()
            Label:
                size_hint_x: 0.2
                text: str("length")
    BoxLayout:
        pos_hint:{"right":1, "top":1}
        size_hint_x: 0.5
        size_hint_y: 0.4
        orientation: "vertical"
        Label:
            size_hint_y: 0.3
            text: str("D_parts")
        BoxLayout:
            BoxLayout:
                Image:
                    source: 'sample1.jpg'
            Slider:
                id: slider_d
                min: 0
                max: 50
                value: 25
                step: 5
                orientation: 'vertical'
                size_hint_x:0.3        
            Label:
                size_hint_x: 0.1
                text: str(slider_d.value)
        BoxLayout:
            size_hint_y: 0.2
            Label:
                size_hint_x: 0.2
                text: str("name")
            TextInput:
                text:"Hello World"
                size_hint_x:0.3
                color:1,0,0,1
                id: text_d
                multiline: False
                on_text_validate: root.get_text_d()
            Button:
                size_hint_x: 0.2
                text: "ok"
                on_release:
                    root.get_text_d()
            Label:
                size_hint_x: 0.2
                text: str("length")
#    Label:
#        color:1,0,0,1
#        text: str(user_text.text)

<testInput>:

    # BoxLayout:
    #     size_hint: 0.1, 0.2
    #     center_y: root.center_y*0.8
    #     Slider:
    #         id: slider_a
    #         min: 0
    #         max: 100
    #         step: 1
    #         orientation: 'vertical'
    #         #orientation: 'horizontal'
    #         on_touch_move: if self.collide_point(*args[1].pos): root.test_a()
    #     Label:
    #         text: str(slider_a.value)

    # BoxLayout:
    #     size_hint: 0.2, 0.1
    #     center_y: root.center_y*0.6
    #     Slider:
    #         id: slider_b
    #         min: 0
    #         max: 100
    #         step: 1
    #         orientation: 'horizontal'
    #         on_touch_move: if self.collide_point(*args[1].pos): root.test_b()
    #     Label:
    #         text: str(slider_b.value)

    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x - self.width
        center_y: root.center_y
        text: 'BACK'
        on_release:
            root.manager.transition.direction = 'right' 
            root.manager.current = 'start'
    
    Button:
        size_hint: 0.2, 0.1
        center_x: root.center_x*2 - self.width
        center_y: root.center_y
        text: 'serch'
        on_release:
            root.search_com_port()
    
    Button:
        id: sel_btn
        size_hint: 0.2, 0.1
        center_x: root.center_x*4 - self.width
        center_y: root.center_y*1.5
        text: 'select'
        on_release:
            root.select_port()

    Button:
        id: select_box
        size_hint: None, None
        pos_hint: {"center_x": 0.5, "center_y": 0.8 }
        size: 500, 40
        text: "Click me to select port"
        on_release: context_menu.show(*app.root_window.mouse_pos)

    ContextMenu:
        id: context_menu
        visible: False
        #cancel_handler_widget: layout

        ContextMenuTextItem:
            text: "none"
            on_release: context_menu.hide()